Fix ghc-9.12 nix build
This fixes builds for the dependencies haskell-language-server and
proto-lens.

proto-lens fails with:

    Error: [Cabal-6661]
    filepath wildcard 'proto-lens-imports/google/protobuf/descriptor.proto'
    refers to the directory 'proto-lens-imports/google/protobuf', which does not exist or is not a directory.
    filepath wildcard 'proto-lens-imports/google/protobuf/descriptor.proto'
    does not match any files.

However, SRP is currently required because the released version does not
support ghc-9.12.

The previous haskell-language-server did not support ghc-9.12, so we are
upgrading it to the latest version