PoolOfflineFetchError: use current time for retries fetch time
Instead of previous error fetch time.

Cherry-pick of 0f134496cd3e6d794b6c83cb743ce026ecb19e80 from master.