postgresql-setup.sh: drop_db function to include cascade
Fix this error:  ./postgresql-setup.sh --recreatedb
ERROR:  cannot drop desired object(s) because other objects depend on them
DETAIL:  function f_mints(character varying) depends on type int65type
HINT:  Use DROP ... CASCADE to drop the dependent objects too.