fix(nix): Temporarily disable linking with systemd
Fixes:

error: The Haskell package set does not contain the package: lobemo-scribe-systemd (build
dependency).  If you are using Stackage, make sure that you are using a snapshot that
contains the package. Otherwise you may need to update the Hackage snapshot you are using,
usually by updating haskell.nix.