Fix nix devShell ghc912 musl
Fixes the following error:

 > error: executing '/nix/store/xy4jjgw87sbgwylm5kn047d9gkbhsr9x-bash-5.2p37/bin/bash':
 > Argument list too long

We are attempting to reduce the number of packages required for the
shell by disabling haddock and hoogle. Longer term, it would be better
to disable devShells for cross builds entirely.

Signed-off-by: Kostas Dermentzis <kostas.dermentzis@iohk.io>